name: CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install dependencies (if needed)
      # Add apt-get commands here if your project needs extra libs
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # Step 3: Build with make
      - name: Build project
        run: make

      # Optional: Clean after build
      - name: Clean build
        run: make clean
